name: firebase_performance_example
description: Demonstrates how to use the firebase_performance plugin.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  firebase_core: ^2.7.1
  firebase_performance: ^0.9.0+15
  flutter:
    sdk: flutter
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
