name: firebase_app_check_platform_interface
description: A common platform interface for the firebase_app_check plugin.
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_app_check/firebase_app_check_platform_interface
version: 0.0.5+16

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  _flutterfire_internals: ^1.0.17
  firebase_core: ^2.7.1
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  firebase_core_platform_interface: ^4.5.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
