name: cloud_firestore
description:
  Flutter plugin for Cloud Firestore, a cloud-hosted, noSQL database with
  live synchronization and offline support on Android and iOS.
homepage: https://firebase.google.com/docs/firestore
repository: https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore
version: 4.4.4

false_secrets:
  - example/**
  - dartpad/**

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  cloud_firestore_platform_interface: ^5.11.4
  cloud_firestore_web: ^3.3.4
  collection: ^1.0.0
  firebase_core: ^2.7.1
  firebase_core_platform_interface: ^4.5.3
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.firestore
        pluginClass: FlutterFirebaseFirestorePlugin
      ios:
        pluginClass: FLTFirebaseFirestorePlugin
      macos:
        pluginClass: FLTFirebaseFirestorePlugin
      web:
        default_package: cloud_firestore_web
