name: cloud_firestore_odm_generator_integration_test
version: 1.0.0-dev.1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.4
  cloud_firestore_odm: ^1.0.0-dev.51
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.0
  json_annotation: ^4.6.0
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.0
  cloud_firestore_odm_generator: ^1.0.0-dev.51
  flutter_test:
    sdk: flutter
  freezed: ^2.0.0
  json_serializable: ">=6.3.0 <7.0.0"

flutter:
  uses-material-design: false
