name: firebase_core
description: Flutter plugin for Firebase Core, enabling connecting to multiple
  Firebase apps.
homepage: https://firebase.google.com/docs/flutter/setup
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_core/firebase_core
version: 2.7.1

false_secrets:
  - example/**

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_core_platform_interface: ^4.5.3
  firebase_core_web: ^2.2.2
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.core
        pluginClass: FlutterFirebaseCorePlugin
      ios:
        pluginClass: FLTFirebaseCorePlugin
      macos:
        pluginClass: FLTFirebaseCorePlugin
      web:
        default_package: firebase_core_web

firebase:
  google_services_gradle_plugin_version: "4.3.10"
  crashlytics_gradle_plugin_version: "2.8.1"
  performance_gradle_plugin_version: "1.4.1"
