name: firebase_app_check_web
description: The web implementation of firebase_auth
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_app_check/firebase_app_check_web
version: 0.0.7+16

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  _flutterfire_internals: ^1.0.17
  firebase_app_check_platform_interface: ^0.0.5+16
  firebase_core: ^2.7.1
  firebase_core_web: ^2.2.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  firebase_app_check: ^0.1.1+13
  firebase_core_platform_interface: ^4.5.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAppCheckWeb
        fileName: firebase_app_check_web.dart
