name: cloud_functions_example
description: Demonstrates how to use the cloud_functions plugin.

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.4'

dependencies:
  cloud_functions: ^4.0.12
  cupertino_icons: ^0.1.2
  firebase_core: ^2.7.1
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
