name: cloud_functions
description: A Flutter plugin allowing you to use Firebase Cloud Functions.
version: 4.0.12
homepage: https://firebase.google.com/docs/functions
repository: https://github.com/firebase/flutterfire/tree/master/packages/cloud_functions/cloud_functions

false_secrets:
  - example/**

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  cloud_functions_platform_interface: ^5.1.31
  cloud_functions_web: ^4.3.20
  firebase_core: ^2.7.1
  firebase_core_platform_interface: ^4.5.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.functions
        pluginClass: FlutterFirebaseFunctionsPlugin
      ios:
        pluginClass: FLTFirebaseFunctionsPlugin
      macos:
        pluginClass: FLTFirebaseFunctionsPlugin
      web:
        default_package: cloud_functions_web
