name: cloud_functions_web
description: The web implementation of cloud_functions
homepage: https://github.com/firebase/flutterfire/tree/master/packages/cloud_functions/cloud_functions_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/cloud_functions/cloud_functions_web

version: 4.3.20

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  cloud_functions_platform_interface: ^5.1.31
  firebase_core: ^2.7.1
  firebase_core_web: ^2.2.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  firebase_core_platform_interface: ^4.5.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseFunctionsWeb
        fileName: cloud_functions_web.dart
