name: cloud_firestore_web
description: The web implementation of cloud_firestore
homepage: https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_web

version: 3.3.4

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  _flutterfire_internals: ^1.0.17
  cloud_firestore_platform_interface: ^5.11.4
  collection: ^1.0.0
  firebase_core: ^2.7.1
  firebase_core_web: ^2.2.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  firebase_core_platform_interface: ^4.5.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseFirestoreWeb
        fileName: cloud_firestore_web.dart
