name: firebase_firestore

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/firebase_core/**"
      - "packages/cloud_firestore/**"
      - ".github/workflows/firebase_firestore.yaml"
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"

env:
  FLUTTERFIRE_PLUGIN_SCOPE: "*cloud_firestore*"
  FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE: "*cloud_firestore_example*"

jobs:
  android:
    runs-on: macos-12
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@dd3c344d731938d2ab2567a261f54a19a68b5f6a
        with:
          run-bootstrap: false
          melos-version: '3.0.0-dev.0'
      - name: "Install Tools"
        run: |
          sudo npm i -g firebase-tools
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-example.sh android
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: "Drive Example"
        uses: reactivecircus/android-emulator-runner@50986b1464923454c95e261820bc626f38490ec0
        with:
          api-level: 28
          arch: x86_64
          # Firebase Firestore works without Google Play Services, so we don't use the `googleapis`
          # emulator target as it's considerably slower on CI.
          target: default
          profile: Nexus 5X
          script: ./.github/workflows/scripts/drive-example.sh android

  apple:
    runs-on: macos-12
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
        with:
          # TODO(Lyokone): upgrade to stable when https://github.com/flutter/flutter/issues/118469 is closed
          flutter-version: '3.3.10'
          cache: true
      - uses: bluefireteam/melos-action@dd3c344d731938d2ab2567a261f54a19a68b5f6a
        with:
          run-bootstrap: false
          melos-version: '3.0.0-dev.0'
      - name: "Install Tools"
        run: |
          sudo npm i -g firebase-tools
      - name: "Build iOS Example"
        run: ./.github/workflows/scripts/build-example.sh ios
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: "Drive iOS Example"
        run: ./.github/workflows/scripts/drive-example.sh ios
      - name: "Build MacOS Example"
        run: ./.github/workflows/scripts/build-example.sh macos
      - name: "Reset Firestore Emulator"
        run: cd ./.github/workflows/scripts && ./reset-firestore-emulator.sh
      - name: "Drive MacOS Example"
        run: ./.github/workflows/scripts/drive-example.sh macos

  web:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@dd3c344d731938d2ab2567a261f54a19a68b5f6a
        with:
          run-bootstrap: false
          melos-version: '3.0.0-dev.0'
      - name: "Install Tools"
        run: |
          sudo npm i -g firebase-tools
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: "Drive Example"
        run: ./.github/workflows/scripts/drive-example.sh web
