name: firebase_performance

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/firebase_performance/**"
      - ".github/workflows/firebase_performance.yaml"
      # Ensure this workflow runs if the Firebase Android SDK version gets bumped.
      - "packages/firebase_core/firebase_core/android/gradle.properties"
      # Ensure this workflow runs if the Firebase iOS SDK version gets bumped.
      - "packages/firebase_core/firebase_core/ios/firebase_sdk_version.rb"
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"

env:
  FLUTTERFIRE_PLUGIN_SCOPE: "*firebase_performance*"
  FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE: "*firebase_performance_example*"

jobs:
  android:
    if: github.event_name == 'pull_request'
    runs-on: macos-12
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@dd3c344d731938d2ab2567a261f54a19a68b5f6a
        with:
          melos-version: '3.0.0-dev.0'
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-example.sh android
      - name: "Drive Example"
        uses: reactivecircus/android-emulator-runner@50986b1464923454c95e261820bc626f38490ec0
        with:
          api-level: 28
          arch: x86_64
          target: google_apis
          profile: Nexus 5X
          script: ./.github/workflows/scripts/drive-example.sh android

  ios:
    runs-on: macos-12
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@dd3c344d731938d2ab2567a261f54a19a68b5f6a
        with:
          melos-version: '3.0.0-dev.0'
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-example.sh ios
      - name: "Drive Example"
        run: ./.github/workflows/scripts/drive-example.sh ios
